version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - .:/app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: next_basket_users
      DB_USERNAME: muze
      DB_PASSWORD: password
  
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: next_basket_users
      MYSQL_USER: muze
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
